language: node_js
node_js: 8
jobs:
  include:
    - stage: lint
      script:
        - yarn run lint
    - stage: build
      script:
        - cp .env.example .env
        - NODE_ENV=production yarn run build
